version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/joway/loki
    steps:
      - checkout
      - run: sudo apt update && sudo apt install -y gcc
      - run: ./bin/dep.sh
      - run: make test
      - run: bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  pipeline:
    jobs:
      - build
